spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sfg_prod
    username: sfg_prod_user
    password: ninja
    platform: mysql
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    database: mysql